# Generated by Django 5.2.5 on 2025-08-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="event",
            table="Event",
        ),
        migrations.AlterModelTable(
            name="order",
            table="Order",
        ),
        migrations.AlterModelTable(
            name="ticket",
            table="Ticket",
        ),
    ]
