# Generated by Django 5.2.5 on 2025-08-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_event_table_alter_order_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='max_quantity',
        ),
        migrations.AddField(
            model_name='event',
            name='max_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
