# Generated by Django 5.2.5 on 2025-08-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
    ]
