# Generated by Django 5.2.5 on 2025-08-18 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_remove_ticket_order_order_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tickets',
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticket.order'),
        ),
    ]
